CREATE TABLE folder (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE files (
    id VARCHAR(50) PRIMARY KEY,
    folder_id VARCHAR(50),
    name VARCHAR(255) NOT NULL,
    FOREIGN KEY (folder_id) REFERENCES folder(id) ON DELETE CASCADE
);